name: automerge
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened

  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.3"
        with:
          github-token: ${{ secrets.PAT }}
