name: make change and create pr
on:
  workflow_dispatch:
  # push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make changes to pull request
      run: date +%s > report.txt

    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
        branch: pr-branch
        commit-message: commit message
        title: the pr title
        body: the pr body
    - name: delay
      run: sleep 10

    - name: automerge
      if: ${{ steps.cpr.outputs.pull-request-number }}
      uses: "pascalgn/automerge-action@v0.16.3"
      env:
        GITHUB_TOKEN: "{{ secrets.PAT }}"
        MERGE_LABELS: ""
        MERGE_DELETE_BRANCH: "true"
        PULL_REQUEST: ${{ steps.cpr.outputs.pull-request-number }}
