name: Automated Workflow

on:
  workflow_dispatch:
  # push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make changes to pull request
      run: date +%s > report.txt

    - name: Create pull request
      uses: peter-evans/create-pull-request@v6
      with:
        branch: pr-branch
        commit-message: commit message
        title: the pr title
        body: the pr body
