name: Automated Workflow

on:
  workflow_dispatch:
  pull_request:
  # push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make changes to pull request
      run: date +%s > report.txt

    - name: Create pull request
      uses: peter-evans/create-pull-request@v6
      with:
        branch: pr-branch

    - name: Auto-merge pull request
      if: github.event_name == 'pull_request' && github.event.action == 'opened' # 仅当新建合并请求时触发
      uses: "pascalgn/automerge-action@v0.16.3"
      with:
        github-token: ${{ secrets.PAT }}
