name: Auto-merge Dependabot
on: pull_request

jobs:
  auto-merge:
      runs-on: ubuntu-latest
      steps:
        - name: Enable Pull Request Automerge
          run: gh pr merge --merge --auto "1"
          env:
            GH_TOKEN: ${{ secrets.PAT }}
