name: Auto-merge Dependabot
on: 
  workflow_dispatch:
  pull_request:

jobs:
  auto-merge:
      runs-on: ubuntu-latest
      steps:
        - name: Enable Pull Request Automerge
          run: gh pr merge --merge --auto "7"
          env:
            GH_TOKEN: ${{ secrets.PAT }}
